{"name": "test_BBR_Replay[Chrome]", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <python_pytest.Tests.test_session_search.Test_Session_Creation_BBR_Replay object at 0x7fac4f14ef10>\n\n    def test_BBR_Replay(self):\n        self.bbr_replay = BBR_Replay(self.driver)\n>       self.bbr_replay.do_replay_play()\n\npython_pytest/Tests/test_session_search.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npython_pytest/Pages/BBR_Replay.py:17: in do_replay_play\n    self.do_click(self.Replay_Session)\npython_pytest/Pages/BasePage.py:17: in do_click\n    WebDriverWait(self.driver,20).until(EC.visibility_of_element_located(by_locator)).click()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"4f53c64a99843b16326b8a5e92c8820c\")>\nmethod = <selenium.webdriver.support.expected_conditions.visibility_of_element_located object at 0x7fac4f14e9d0>, message = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nvenv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py:80: TimeoutException"}, "parameters": [{"name": "init_driver", "value": "'Chrome'"}], "start": 1658228581819, "stop": 1658228601880, "uuid": "30c8d58a-5a49-426e-a528-4b63385c2310", "historyId": "dcc2a18dc477b21668dfe9aeda879ecd", "testCaseId": "d4ec0503fbf86f96831c43ccd2b0edc9", "fullName": "python_pytest.Tests.test_session_search.Test_Session_Creation_BBR_Replay#test_BBR_Replay", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "parentSuite", "value": "python_pytest.Tests"}, {"name": "suite", "value": "test_session_search"}, {"name": "subSuite", "value": "Test_Session_Creation_BBR_Replay"}, {"name": "host", "value": "ip-10-234-242-83.ec2.internal"}, {"name": "thread", "value": "28285-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "python_pytest.Tests.test_session_search"}]}